fix(cmake): try cblas library before blas for linking
 `src/CMakeLists.txt` checks for `cblas.h` and the blas library
 separately.

 But `cblas.h` is a part of cblas, not blas.

 This can result in linking errors, as a reference to `cblas_sgemm`
 is not found, because libblas doesn't have the symbol:

     mel.cpp:(.text+0x19a8): undefined reference to `cblas_sgemm'

 This commit looks for the cblas library first, and links against it
 if found. Otherwise, the old behavior of trying blas is done.

Signed-off-by: Bergmann Atmet <BergmannAtmet@github>